### ISSUE TITLE
panic: interface conversion: config.InterpolatedVariable is *config.LocalVariable, not *config.ResourceVariable

### ISSUE THREAD

**Issue by clstokes** [pulumi/tf2pulumi#151]
Received a panic while converting some Terraform code. I will provide the code out-of-band as its proprietary.

#### Command
```
tf2pulumi --allow-missing-plugins --record-locations --allow-missing-variables
```

#### Version
https://github.com/pulumi/tf2pulumi/releases/tag/v0.6.0

#### Stack trace
```
panic: interface conversion: config.InterpolatedVariable is *config.LocalVariable, not *config.ResourceVariable

goroutine 1 [running]:
github.com/pulumi/tf2pulumi/gen/nodejs.(*generator).resourceMode(0xc00030e630, 0xc0004713b0, 0x262ebc0)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/nodejs/generator.go:188 +0x170
github.com/pulumi/tf2pulumi/gen/nodejs.(*generator).getNestedPropertyAccessElementInfo(0xc00030e630, 0xc0004713b0, 0xc00082db70, 0x262ebc0, 0xc00000e800, 0x0, 0x0, 0xc00082db70)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/nodejs/hil.go:125 +0x75
github.com/pulumi/tf2pulumi/gen/nodejs.(*generator).canLiftVariableAccess(0xc00030e630, 0xc0004713b0, 0x0)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/nodejs/lower.go:64 +0x39
github.com/pulumi/tf2pulumi/gen/nodejs.(*generator).parseInterpolate(0xc00030e630, 0xc000b24400, 0x8, 0x8, 0x263b520, 0xc0009e2090, 0x0, 0x0)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/nodejs/lower.go:134 +0x155
github.com/pulumi/tf2pulumi/gen/nodejs.(*generator).lowerProxyApplies.func1(0x262ea80, 0xc000b263f0, 0x9, 0x23564c8, 0xc00082db50, 0xc0007cd320)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/nodejs/lower.go:174 +0x12d
github.com/pulumi/tf2pulumi/il.visitBoundCall(0xc000b263f0, 0x23564c8, 0xc00082db50, 0xc000b263f0, 0x0, 0x0, 0x0)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/il/boundTree_visitor.go:50 +0xab
github.com/pulumi/tf2pulumi/il.VisitBoundNode(0x262ea80, 0xc000b263f0, 0x23564c8, 0xc00082db50, 0xc0005a8f38, 0xc000b1ff80, 0x1, 0x2)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/il/boundTree_visitor.go:213 +0x418
github.com/pulumi/tf2pulumi/il.visitBoundMapProperty(0xc0009e2150, 0x23564c8, 0xc00082db50, 0xc0009e2150, 0x0, 0x0, 0x100e118)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/il/boundTree_visitor.go:110 +0x245
github.com/pulumi/tf2pulumi/il.VisitBoundNode(0x262ec00, 0xc0009e2150, 0x23564c8, 0xc00082db50, 0x1f18540, 0xc000b26240, 0x1f18460, 0xc000b26240)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/il/boundTree_visitor.go:225 +0x32d
github.com/pulumi/tf2pulumi/gen/nodejs.(*generator).lowerProxyApplies(0xc00030e630, 0x262ec00, 0xc0009e2150, 0xc0009e2150, 0x0, 0x0, 0x0)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/nodejs/lower.go:180 +0x7b
github.com/pulumi/tf2pulumi/gen/nodejs.(*generator).computeProperty(0xc00030e630, 0x262ec00, 0xc0009e2150, 0x262ec01, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/nodejs/generator.go:252 +0x3e9
github.com/pulumi/tf2pulumi/gen/nodejs.(*generator).generateResource(0xc00030e630, 0xc000485e40, 0xc00030e630, 0xc000a24a50)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/nodejs/generator.go:765 +0x1287
github.com/pulumi/tf2pulumi/gen/nodejs.(*generator).GenerateResource(0xc00030e630, 0xc000485e40, 0x2642240, 0xc00030e630)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/nodejs/generator.go:858 +0xa6
github.com/pulumi/tf2pulumi/gen.generateDependency(0x263b7c0, 0xc000485e40, 0x2642240, 0xc00030e630, 0xc00051b2d0, 0xc00051b330, 0x0, 0x0)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/gen.go:112 +0x36f
github.com/pulumi/tf2pulumi/gen.generateNode(...)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/gen.go:85
github.com/pulumi/tf2pulumi/gen.generateInnerNodes(0xc000647d80, 0x2642240, 0xc00030e630, 0x11, 0x0)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/gen.go:213 +0xb37
github.com/pulumi/tf2pulumi/gen.generateModuleDef(0xc000647d80, 0x2642240, 0xc00030e630, 0x1, 0x0)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/gen.go:238 +0x2e0
github.com/pulumi/tf2pulumi/gen.Generate(0xc00057afd0, 0x1, 0x1, 0x2642240, 0xc00030e630, 0x22e9045, 0x1)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/gen/gen.go:264 +0xa4
github.com/pulumi/tf2pulumi/convert.Convert(0x1010101, 0x0, 0x0, 0x22e9045, 0x1, 0x25fb400, 0xc000010010, 0x0, 0x0, 0x0, ...)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/convert/convert.go:145 +0x538
main.main.func1(0xc000327b80, 0xc000328cf0, 0x0, 0x3, 0x0, 0x0)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/main.go:56 +0xe3
github.com/pulumi/tf2pulumi/vendor/github.com/spf13/cobra.(*Command).execute(0xc000327b80, 0xc00003c0d0, 0x3, 0x3, 0xc000327b80, 0xc00003c0d0)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/pulumi/tf2pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000327b80, 0xc00054bf58, 0x1, 0x1)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/pulumi/tf2pulumi/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/Users/pgavlin/dev/go/src/github.com/pulumi/tf2pulumi/main.go:88 +0x565
```

**Comment by Frassle** [comment]
This converter is deprecated and the [new converter](https://www.pulumi.com/blog/converting-full-terraform-programs-to-pulumi/) is a full rewrite, it's likely this doesn't apply.
