### ISSUE TITLE
[Feature] Support for JSON for terraform 0.12

### ISSUE THREAD

**Issue by tmccombs** [pulumi/tf2pulumi#201]
Attempting to import from terraform configuration that contains json .tf.json files fails with "JSON configuration is not supported". I'd like to be able to import from configuration that has .tf.json files in it.

**Comment by lukehoban** [comment]
In the new converted - this still fails - now with this error:

```
> pulumi convert --from terraform --language typescript --out ts2
Converting from terraform...
panic: fatal: An assertion has failed: *json.body was not a hclsyntax.Body

goroutine 43 [running]:

github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.70.1-0.20230611235120-feb5153187d1/go/common/util/contract/failfast.go:23

github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x28?, {0x1015febdc?, 0x140005e5528?}, {0x140005e5820?, 0x1030d6020?, 0x1038745e0?})

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.70.1-0.20230611235120-feb5153187d1/go/common/util/contract/assert.go:35 +0xe0

github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.convertBody(0x1015d4584?, 0x14000844780, {0x14001e3c5a0, 0x14}, {0x10208f100?, 0x140004d2648?})

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.2-0.20230613134813-d9a243d1ef36/pkg/tf2pulumi/convert/tf.go:1479 +0xe0

github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.convertManagedResources(0x101d15800?, {0x102075b00, 0x140004e6df0}, 0x14000844780, 0x14000269380, 0x14002234030)

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.2-0.20230613134813-d9a243d1ef36/pkg/tf2pulumi/convert/tf.go:2008 +0x6bc

github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.translateModuleSourceCode(0x14000254430?, {0x10209a0e0, 0x1030d4008}, {0x14000058980, 0x1c}, {0x10209a060?, 0x140004ea500?}, {0x101aba680, 0x1}, {0x102075b00?, ...})

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.2-0.20230613134813-d9a243d1ef36/pkg/tf2pulumi/convert/tf.go:2722 +0x31b8

github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.TranslateModule(...)

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.2-0.20230613134813-d9a243d1ef36/pkg/tf2pulumi/convert/tf.go:2808

main.(*tfConverter).ConvertProgram(0x14000b33718, {0x100087f28?, 0x14000b33748?}, 0x140004e8d50)

	/Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/cmd/pulumi-converter-terraform/main.go:57 +0x1c8

github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*converterServer).ConvertProgram(0x140008abfe0, {0x10208e370, 0x140004e8d20}, 0x1400012eb40)

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.70.1-0.20230611235120-feb5153187d1/go/common/resource/plugin/converter_server.go:64 +0xec

github.com/pulumi/pulumi/sdk/v3/proto/go._Converter_ConvertProgram_Handler.func1({0x10208e370, 0x140004e8d20}, {0x101f0de60?, 0x1400012eb40})

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.70.1-0.20230611235120-feb5153187d1/proto/go/converter_grpc.pb.go:122 +0x74

github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x10208e370, 0x140004e89c0}, {0x101f0de60, 0x1400012eb40}, 0x140004ea200, 0x140004d23a8)

	/Users/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x308

github.com/pulumi/pulumi/sdk/v3/proto/go._Converter_ConvertProgram_Handler({0x101db6320?, 0x140008abfe0}, {0x10208e370, 0x140004e89c0}, 0x140009b4150, 0x140008abee0)

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.70.1-0.20230611235120-feb5153187d1/proto/go/converter_grpc.pb.go:124 +0x138

google.golang.org/grpc.(*Server).processUnaryRPC(0x14000696b40, {0x102097fc0, 0x14000500680}, 0x14000a9e120, 0x14000963080, 0x10305c418, 0x0)

	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1337 +0xc90

google.golang.org/grpc.(*Server).handleStream(0x14000696b40, {0x102097fc0, 0x14000500680}, 0x14000a9e120, 0x0)

	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1714 +0x82c

google.golang.org/grpc.(*Server).serveStreams.func1.1()

	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:959 +0x84

created by google.golang.org/grpc.(*Server).serveStreams.func1

	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:957 +0x16c
```
