### ISSUE TITLE
fatal error on convert

### ISSUE THREAD

**Issue by TimoKramer** [pulumi/tf2pulumi#217]
Hi there,
I am trying to convert an ECS deployment with tf2pulumi but it fails. Is there something I am doing wrong or is there an easy fix?

```
panic: fatal: A failure has occurred

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.3.1-0.20200610172153-45a901d3e77c/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Fail(...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.3.1-0.20200610172153-45a901d3e77c/go/common/util/contract/fail.go:25
github.com/pulumi/tf2pulumi/convert.convertTF12(0xc0005d8300, 0xe, 0x10, 0x10000, 0x0, 0x0, 0x1919e40, 0xc0005d0080, 0x0, 0x0, ...)
	/home/runner/work/tf2pulumi/tf2pulumi/convert/tf12.go:155 +0x1e0d
github.com/pulumi/tf2pulumi/convert.Convert(0x10000, 0x0, 0x0, 0x1919e40, 0xc0005d0080, 0x0, 0x0, 0x0, 0x18dd200, 0x2366be0, ...)
	/home/runner/work/tf2pulumi/tf2pulumi/convert/convert.go:107 +0x3d7
main.main.func1(0xc0005e62c0, 0xc000418180, 0x0, 0x4, 0x0, 0x0)
	/home/runner/work/tf2pulumi/tf2pulumi/main.go:52 +0xe6
github.com/spf13/cobra.(*Command).execute(0xc0005e62c0, 0xc0000ce010, 0x4, 0x4, 0xc0005e62c0, 0xc0000ce010)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005e62c0, 0xc00087ff50, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/tf2pulumi/tf2pulumi/main.go:117 +0x588
```

Here is the terraform code I want to convert: https://github.com/lispyclouds/helidon-crux-api/tree/main/deploy

Version of tf2pulumi `v0.9.0`

**Comment by dansimau** [comment]
I have the same issue with v0.11.1.

**Comment by bradyburke** [comment]
I have the same issue with v0.11.1.

**Comment by lukehoban** [comment]
With the [new converter](https://www.pulumi.com/blog/converting-full-terraform-programs-to-pulumi/) - this no longer panics, but does hit a few errors:

```
pulumi convert --from terraform --language typescript --out ts4
Converting from terraform...
warning: /Users/lukehoban/dd/awscs/tf/helidon-crux-api/deploy/main.tf:1,1-15: Failed to evaluate provider config; Could not evaluate expression for aws:region
Converting to nodejs...
================================================================================
The Pulumi CLI encountered a code generation error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.74.0
error: network.pp:21,5-20: cannot iterate over a value of type string;
error: network.pp:8,5-20: cannot iterate over a value of type string;
error: network.pp:45,5-20: cannot iterate over a value of type string;
error: network.pp:51,5-20: cannot iterate over a value of type string;
error: network.pp:59,5-20: cannot iterate over a value of type string;
error: network.pp:70,5-20: cannot iterate over a value of type string;
error: could not generate output program
```
