### ISSUE TITLE
unknown function 'toset'

### ISSUE THREAD

**Issue by naveensrinivasan** [pulumi/tf2pulumi#226]
I am trying to export to pulumi and this is the error I ran into. https://github.com/ossf/package-feeds/tree/main/terraform

```
tf2pulumi  --allow-missing-plugins --target-language go
Error: unknown function 'toset'

  on feeds.tf line 32:
  (source code not available)

Warning: default provider configuration is not supported

  on feeds.tf line 0:
  (source code not available)

Error: unknown function 'toset'

  on feeds.tf.pp line 21:
  22:   range           = toset(services)

Error: undefined variable range

  on feeds.tf.pp line 24:
  25:   service            = range.value
  ```

**Comment by naveensrinivasan** [comment]
Ran into panic
```
panic: invalid Go source code:

package main

import (

"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
"github.com/pulumi/pulumi-gcp/sdk/v4/go/gcp/cloudrun"
"github.com/pulumi/pulumi-gcp/sdk/v4/go/gcp/cloudscheduler"
"github.com/pulumi/pulumi-gcp/sdk/v4/go/gcp/projects"
"github.com/pulumi/pulumi-gcp/sdk/v4/go/gcp/pubsub"
"github.com/pulumi/pulumi-gcp/sdk/v4/go/gcp/serviceAccount"
"github.com/pulumi/pulumi-gcp/sdk/v4/go/gcp/storage"
)
func main() {
pulumi.Run(func(ctx *pulumi.Context) error {
services := []string{
"cloudbuild.googleapis.com",
"run.googleapis.com",
"cloudscheduler.googleapis.com",
"cloudresourcemanager.googleapis.com",
};
run-invoker-account, err := serviceAccount.NewAccount(ctx, "run-invoker-account", &serviceAccount.AccountArgs{
AccountId: pulumi.String("run-invoker-sa"),
DisplayName: pulumi.String("Feed Run Invoker"),
})
if err != nil {
return err
}
run-invoker-iam, err := projects.NewIAMMember(ctx, "run-invoker-iam", &projects.IAMMemberArgs{
Role: pulumi.String("roles/run.invoker"),
Member: run-invoker-account.Email.ApplyT(func(email string) (string, error) {
return "TODO: TODO multi part template expressions", nil
}).(pulumi.StringOutput),
})
if err != nil {
return err
}
feed-topic, err := pubsub.NewTopic(ctx, "feed-topic", &pubsub.TopicArgs{
Name: pulumi.String("feed-topic"),
})
if err != nil {
return err
}
feed-functions-bucket, err := storage.NewBucket(ctx, "feed-functions-bucket", &storage.BucketArgs{
Name: pulumi.String("TODO: TODO multi part template expressions"),
ForceDestroy: pulumi.Bool(true),
})
if err != nil {
return err
}
run-pypi, err := cloudrun.NewService(ctx, "run-pypi", &cloudrun.ServiceArgs{
Name: pulumi.String("pypi-run-srv"),
Location: pulumi.String(region),
Template: &cloudrun.ServiceTemplateArgs{
Spec: &cloudrun.ServiceTemplateSpecArgs{
Containers: cloudrun.ServiceTemplateSpecContainerArray{
&cloudrun.ServiceTemplateSpecContainerArgs{
Image: pulumi.String("TODO: TODO multi part template expressions"),
Envs: cloudrun.ServiceTemplateSpecContainerEnvArray{
&cloudrun.ServiceTemplateSpecContainerEnvArgs{
Name: pulumi.String("OSSMALWARE_TOPIC_URL"),
Value: feed-topic.ID().ApplyT(func(id string) (string, error) {
return "TODO: TODO multi part template expressions", nil
}).(pulumi.StringOutput),
},
},
},
},
},
},
})
if err != nil {
return err
}
trigger-pypi-scheduler, err := cloudscheduler.NewJob(ctx, "trigger-pypi-scheduler", &cloudscheduler.JobArgs{
Name: pulumi.String("trigger-pypi-scheduler"),
Description: pulumi.String("The scheduler that triggers fetching new PyPI packages"),
Schedule: pulumi.String("*/5 * * * *"),
HttpTarget: &cloudscheduler.JobHttpTargetArgs{
HttpMethod: pulumi.String("POST"),
Uri: run-pypi.Statuses.ApplyT(func(statuses []cloudrun.ServiceStatus) (string, error) {
return statuses[0].Url, nil
}).(pulumi.StringOutput),
OidcToken: &cloudscheduler.JobHttpTargetOidcTokenArgs{
ServiceAccountEmail: run-invoker-account.Email,
},
},
})
if err != nil {
return err
}
return nil
})
}


goroutine 1 [running]:
github.com/pulumi/pulumi/pkg/v2/codegen/go.GenerateProgram(0xc000cd6c40, 0x1, 0x1, 0x0, 0xc00000e698, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.3.1-0.20200610172153-45a901d3e77c/codegen/go/gen_program.go:52 +0x4e9
github.com/pulumi/tf2pulumi/convert.Convert(0x10001, 0x0, 0x0, 0x251ab60, 0xc00037f900, 0x0, 0x0, 0x0, 0x24ddc80, 0x2f6a8c0, ...)
	/home/runner/work/tf2pulumi/tf2pulumi/convert/convert.go:133 +0xcce
main.main.func1(0xc00013b600, 0xc0004d0ba0, 0x0, 0x3, 0x0, 0x0)
	/home/runner/work/tf2pulumi/tf2pulumi/main.go:52 +0xe6
github.com/spf13/cobra.(*Command).execute(0xc00013b600, 0xc00003a0d0, 0x3, 0x3, 0xc00013b600, 0xc00003a0d0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc00013b600, 0xc0007bff50, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/tf2pulumi/tf2pulumi/main.go:117 +0x588
```

**Comment by Frassle** [comment]
Tracked by other issues for builtins.
