### ISSUE TITLE
Fatal error trying to convert Terraform HCL project to Pulumi

### ISSUE THREAD

**Issue by fhperuchi** [pulumi/tf2pulumi#240]
I'm trying to convert an AWS resources Terraform project to Pulumi and I got this error running these commands inside the directory containing my Terraform project (`.tf`) files

Pulumi version:
```
$ pulumi version
v3.6.0
```

Terraform binary version:
```
$ terraform version
Terraform v0.15.1
on linux_amd64
```

Terraform state version:
```
$ cat terraform.tfstate | head -n 5 
{
  "version": 4,
  "terraform_version": "0.15.1",
  "serial": 588,
  "lineage": "759316b8-3dae-9ada-76e4-47cf6b19f68f",
```

## Steps to reproduce

1.
```
$ npm install @pulumi/terraform

added 1 package, and audited 118 packages in 894ms

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
2.
```
$ npm install @pulumi/aws

added 1 package, and audited 118 packages in 894ms

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```
3.
```
$ pulumi new typescript -f        
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name: (aws) 
project description: (A minimal TypeScript Pulumi program) 
Created project 'aws'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
stack name: (dev) 
Created stack 'dev'

Installing dependencies...

removed 18 packages, and audited 100 packages in 758ms

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Finished installing dependencies

Your new project is ready to go! 

To perform an initial deployment, run 'pulumi up'
```
4.
```
$ tf2pulumi --target-language typescript
panic: fatal: A failure has occurred

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.19.0/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Fail(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.19.0/go/common/util/contract/fail.go:25
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tf2pulumi/convert.convertTF12(0xc0011a3c80, 0xa, 0x10, 0x10000, 0x0, 0x0, 0x19181d8, 0xc0006a25c0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tf2pulumi/convert/tf12.go:156 +0x1e8b
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tf2pulumi/convert.Convert(0x10000, 0x0, 0x0, 0x19181d8, 0xc0006a25c0, 0x0, 0x0, 0x0, 0x18e7ec0, 0x2171180, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tf2pulumi/convert/convert.go:107 +0x3bc
main.main.func1(0xc0004d0000, 0xc0006a2580, 0x0, 0x2, 0x0, 0x0)
        /home/runner/work/tf2pulumi/tf2pulumi/main.go:52 +0x105
github.com/spf13/cobra.(*Command).execute(0xc0004d0000, 0xc00018c010, 0x2, 0x2, 0xc0004d0000, 0xc00018c010)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004d0000, 0xc0009bff50, 0x1, 0x1)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/runner/work/tf2pulumi/tf2pulumi/main.go:117 +0x593
```

**Comment by lukehoban** [comment]
Supporting TF 15 is tracked in https://github.com/pulumi/tf2pulumi/issues/186 and is something we want to get in soon.  In the meantime thought this definitely shouldn't panic.

**Comment by lukehoban** [comment]
Will close this out to track in #186.
