### ISSUE TITLE
not generating lang specific code

### ISSUE THREAD

**Issue by nagkumar** [pulumi/tf2pulumi#262]
### What happened?

when used `tf2pulumi --target-language java` on this code base [https://github.com/pulumi/tf2pulumi/tree/master/tests/terraform/aws/eip
](https://github.com/pulumi/tf2pulumi/tree/master/tests/terraform/aws/eip)

### Steps to reproduce

[https://github.com/pulumi/tf2pulumi/tree/master/tests/terraform/aws/eip
](https://github.com/pulumi/tf2pulumi/tree/master/tests/terraform/aws/eip)

on this code use command  `tf2pulumi ` then say `tf2pulumi --target-language java`

### Expected Behavior

Should generate java or any go code as per the option

### Actual Behavior
```
Previewing update (dev)
View Live: https://app.pulumi.com/nagkumar/hw/dev/previews/52164d5d-2e6a-405d-8859-13ff2f852bbf
     Type                             Name
     pulumi:pulumi:Stack              hw-dev
     ├─ eks:index:Cluster             eks-cluster
 +   │  ├─ eks:index:VpcCni           eks-cluster-vpc-cni
 +   │  ├─ aws:ec2:SecurityGroupRule  eks-cluster-eksExtApiServerClusterI
 +   │  ├─ aws:ec2:SecurityGroupRule  eks-cluster-eksNodeIngressRule
 +   │  ├─ aws:ec2:SecurityGroupRule  eks-cluster-eksNodeInternetEgressRu
 +   │  ├─ aws:ec2:SecurityGroupRule  eks-cluster-eksClusterIngressRule
 +   │  └─ aws:ec2:SecurityGroupRule  eks-cluster-eksNodeClusterIngressRu
     └─ kubernetes:core/v1:ConfigMap  eks-cluster-nodeAccess
Diagnostics:
  pulumi:pulumi:Stack (hw-dev):
    error: Running program [PID: 14772](unknown) failed with an unhandled exception:
    io.grpc.StatusRuntimeException: UNAVAILABLE: error reading from server: read tcp 127.0.0.1:53539->127.0.0.1:53538: use of closed network connection
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
  kubernetes:core/v1:ConfigMap (eks-cluster-nodeAccess):
    error: failed to initialize discovery client: exec plugin: invalid apiVersion "[client.authentication.k8s.io/v1alpha1](http://client.authentication.k8s.io/v1alpha1)"
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by adinath-devangles** [comment]
If we need to import existing resource states from a **.tfstate** file, for pulumi python what are the steps need to follow?

In [documentation](https://www.pulumi.com/docs/guides/adopting/from_terraform/#importing-resources ) for typescript we need to use **import.ts** file. So for python which file we need to use?

**Comment by Frassle** [comment]
The [new converter](https://www.pulumi.com/blog/converting-full-terraform-programs-to-pulumi/) is fully integrated into all languages including java.
