### ISSUE TITLE
Failing test  TestELB2/TypeScript

### ISSUE THREAD

**Issue by t0yv0** [pulumi/tf2pulumi#280]
### What happened?

Skipping the test for now, CI logs later:

```
error: Error: invocation of aws:ec2/getAmi:getAmi returned an error: invoking aws:ec2/getAmi:getAmi: 1 error occurred:
[504](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:505)
	* Your query returned no results. Please change your search criteria and try again.
[505](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:506)

[506](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:507)

[507](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:508)
    at Object.callback (/tmp/p-it-fv-az301-9-tf2pulumi--488c79f6-432045408/node_modules/@pulumi/runtime/invoke.ts:172:33)
[508](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:509)
    at Object.onReceiveStatus (/tmp/p-it-fv-az301-9-tf2pulumi--488c79f6-432045408/node_modules/@grpc/grpc-js/src/client.ts:356:26)
[509](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:510)
    at Object.onReceiveStatus (/tmp/p-it-fv-az301-9-tf2pulumi--488c79f6-432045408/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
[510](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:511)
    at Object.onReceiveStatus (/tmp/p-it-fv-az301-9-tf2pulumi--488c79f6-432045408/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
[511](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:512)
    at /tmp/p-it-fv-az301-9-tf2pulumi--488c79f6-432045408/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
[512](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:513)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[513](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:514)
Resources:
[514](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:515)
    + 3 to create
[515](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:516)

[516](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:517)
    command.go:103: Wrote output to /tmp/p-it-fv-az301-9-tf2pulumi--488c79f6-432045408/command-output/pulumi-preview-initial.20230328-214502.318ee.log
[517](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:518)
    program.go:1218: Destroying stack
[518](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:519)
    command.go:34: **** Invoke '/home/runner/.pulumi/bin/pulumi destroy --non-interactive --yes --skip-preview' in '/tmp/p-it-fv-az301-9-tf2pulumi--488c79f6-432045408'
[519](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:520)
    command.go:103: Wrote output to /tmp/p-it-fv-az301-9-tf2pulumi--488c79f6-432045408/command-output/pulumi-destroy.20230328-214503.97aca.log
[520](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:521)
    command.go:34: **** Invoke '/home/runner/.pulumi/bin/pulumi stack rm --yes' in '/tmp/p-it-fv-az301-9-tf2pulumi--488c79f6-432045408'
[521](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:522)
    command.go:103: Wrote output to /tmp/p-it-fv-az301-9-tf2pulumi--488c79f6-432045408/command-output/pulumi-stack-rm.20230328-214504.72067.log
[522](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:523)
    program.go:689: 
[523](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:524)
        	Error Trace:	program.go:689
[524](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:525)
        	            				tests.go:188
[525](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:526)
        	            				tests.go:114
[526](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:527)
        	Error:      	Received unexpected error:
[527](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:528)
        	            	running test preview, update, and edits: [/home/runner/.pulumi/bin/pulumi preview --non-interactive --diff] did not succeed after 1 tries
[528](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:529)
        	Test:       	TestELB2/TypeScript
[529](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:530)
--- FAIL: TestELB2 (86.91s)
[530](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:531)
    --- PASS: TestELB2/Python (47.69s)
[531](https://github.com/pulumi/tf2pulumi/actions/runs/4547785090/jobs/8018134658?pr=279#step:20:532)
    --- FAIL: TestELB2/TypeScript (39.22s)
```

### Expected Behavior

NA

### Steps to reproduce

NA

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This repo is deprecated, we won't be running tests anymore.
